using System.IO;

namespace SourceGeneration;

public static class SourceGeneration
{
    public const string Header = @"   // <Auto-Generated/>";

    public const string ModAssemblyName = "ZensSky";

    public static readonly char[] DirectorySeparators = [Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar];
}
